-- 80_ventas.sql — Módulo Ventas / TPV (transacciones + líneas)
create table if not exists app.ventas (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references app.tenants(id) on delete cascade,
  numero        bigint generated by default as identity,
  cliente_id    uuid,           -- FK a clientes (rel/)
  cliente_nombre text default 'Contado',
  fecha         date not null default current_date,
  metodo_pago   text not null default 'Tarjeta', -- Tarjeta|Efectivo|Bizum
  total         numeric(12,2) not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_ventas_tenant on app.ventas(tenant_id);
drop trigger if exists trg_ventas_updated on app.ventas;
create trigger trg_ventas_updated before update on app.ventas
  for each row execute function app.set_updated_at();
select app.enable_tenant_rls('app.ventas');

create table if not exists app.venta_lineas (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references app.tenants(id) on delete cascade,
  venta_id     uuid not null references app.ventas(id) on delete cascade,
  producto_id  uuid,            -- FK a productos (rel/)
  servicio_id  uuid,            -- FK a servicios (rel/)
  concepto     text not null,
  cantidad     integer not null default 1,
  precio_unit  numeric(12,2) not null default 0,
  subtotal     numeric(12,2) not null default 0
);
create index if not exists idx_venta_lineas_venta on app.venta_lineas(venta_id);
select app.enable_tenant_rls('app.venta_lineas');
